# -*- coding: utf-8 -*-
import json

DATA = r'''
1|||Your friend suddenly says, “I’m getting married tomorrow.”|||친구가 갑자기 “나 내일 결혼해”라고 말한다.|||헐|||헐 (Heol)|||A stunned reaction like “What…?” when you freeze from sudden shock.|||대박 (Dae-bak)|||Used for positive excitement.|||진짜 (Jin-jja)|||Used to confirm.|||설마 (Seol-ma)|||Used when you doubt something.
2|||You take one bite of food and it’s unbelievably delicious.|||음식을 한 입 먹었는데 충격적으로 맛있다.|||대박|||대박 (Dae-bak)|||“Amazing!” used when something is impressively good.|||헐 (Heol)|||Shock, but not mainly positive praise.|||진짜 (Jin-jja)|||Used to confirm.|||설마 (Seol-ma)|||Used for disbelief.
3|||Your friend tells you something hard to believe, so you check again.|||친구가 믿기 어려운 말을 해서 다시 확인한다.|||진짜|||진짜 (Jin-jja)|||“Really?” used to confirm surprising information.|||대박 (Dae-bak)|||Strong positive reaction.|||헐 (Heol)|||Shock reaction.|||설마 (Seol-ma)|||Doubt, not confirmation.
4|||Your friend says they won the lottery.|||친구가 로또에 당첨됐다고 말한다.|||설마|||설마 (Seol-ma)|||“No way…” used when you strongly doubt something.|||진짜 (Jin-jja)|||Confirmation.|||헐 (Heol)|||Shock.|||대박 (Dae-bak)|||Positive reaction.
5|||Your friend is three hours late and acts like it’s nothing.|||친구가 3시간 늦었는데도 당당하게 행동한다.|||어이없어|||어이없어 (Eo-i-eopseo)|||“This is absurd” when something feels unfair or ridiculous.|||헐 (Heol)|||Shock only.|||대박 (Dae-bak)|||Positive reaction.|||진짜 (Jin-jja)|||Confirmation.
6|||Your friend suggests a plan and you casually agree.|||친구가 계획을 말하고 당신은 가볍게 동의한다.|||응응|||응응 (Eung-eung)|||Casual “yeah / uh-huh” used for light agreement.|||오케이 (O-ke-i)|||More deliberate agreement.|||아니 (A-ni)|||Refusal.|||고마워 (Go-ma-wo)|||Gratitude.
7|||Someone says something unbelievable and you strongly deny it.|||누군가 말도 안 되는 이야기를 해서 강하게 부정한다.|||아니|||아니 (A-ni)|||“No!” used for strong denial.|||헐 (Heol)|||Shock.|||설마 (Seol-ma)|||Doubt, not strong denial.|||대박 (Dae-bak)|||Positive reaction.
8|||Your friend suggests meeting at a specific time and you accept confidently.|||친구가 약속 시간을 제안하고 당신은 확실하게 수락한다.|||오케이|||오케이 (O-ke-i)|||“Okay / Deal” used for clear agreement.|||응응 (Eung-eung)|||More casual.|||아니 (A-ni)|||Refusal.|||헐 (Heol)|||Shock.
9|||Someone helps you fix something.|||누군가 당신을 도와준다.|||고마워|||고마워 (Go-ma-wo)|||“Thank you” used to express gratitude.|||대박 (Dae-bak)|||Positive reaction.|||헐 (Heol)|||Surprise.|||응응 (Eung-eung)|||Agreement.
10|||Your friend tells you they passed an important exam.|||친구가 중요한 시험에 합격했다고 말한다.|||축하해|||축하해 (Chuk-ha-hae)|||“Congratulations!” used to celebrate success.|||고마워 (Go-ma-wo)|||Thanking.|||대박 (Dae-bak)|||Positive reaction.|||헐 (Heol)|||Shock.
11|||Your friend suddenly says, “I quit my job today.”|||친구가 갑자기 “나 오늘 회사 그만뒀어”라고 말한다.|||헐 진짜?|||헐 진짜? (Heol jin-jja?)|||A reaction that starts with shock (“헐”) and immediately moves to confirmation (“Really?”).|||와 대박이다 (Wa dae-bak-i-da)|||Used for strong positive excitement.|||진짜야? (Jin-jja-ya?)|||Used for focused confirmation without shock.|||설마 그게 돼? (Seol-ma geu-ge dwae?)|||Used for disbelief, not confirmation.
12|||You check your phone and see a huge bonus amount.|||폰으로 보너스 금액을 확인했는데 엄청 크다.|||와 대박이다|||와 대박이다 (Wa dae-bak-i-da)|||“Wow, this is amazing!” used for high-energy excitement.|||헐 진짜? (Heol jin-jja?)|||Shock + confirm, not pure excitement.|||진짜야? (Jin-jja-ya?)|||Confirmation.|||설마 그게 돼? (Seol-ma geu-ge dwae?)|||Doubt.
13|||Your friend tells you something hard to believe, so you focus and check.|||친구가 믿기 어려운 말을 해서 집중해서 확인한다.|||진짜야?|||진짜야? (Jin-jja-ya?)|||“Really?” used for focused confirmation without shock.|||헐 진짜? (Heol jin-jja?)|||Shock comes first, not here.|||와 대박이다 (Wa dae-bak-i-da)|||Excited reaction.|||설마 그게 돼? (Seol-ma geu-ge dwae?)|||Doubt, not neutral confirmation.
14|||Your friend says they finished everything in one day.|||친구가 하루 만에 모든 걸 끝냈다고 말한다.|||설마 그게 돼?|||설마 그게 돼? (Seol-ma geu-ge dwae?)|||“No way…” used for strong disbelief.|||진짜야? (Jin-jja-ya?)|||Confirmation.|||헐 진짜? (Heol jin-jja?)|||Shock + confirm.|||와 대박이다 (Wa dae-bak-i-da)|||Positive excitement.
15|||Your friend blames you for something that was clearly their mistake.|||본인 실수인데 오히려 당신에게 책임을 돌린다.|||진짜 어이없다|||진짜 어이없다 (Jin-jja eo-i-eop-da)|||“This is seriously ridiculous” expressing absurdity with evaluation.|||헐 진짜? (Heol jin-jja?)|||Shock + confirm.|||설마 그게 돼? (Seol-ma geu-ge dwae?)|||Doubt.|||와 대박이다 (Wa dae-bak-i-da)|||Positive reaction.
16|||Your friend tells you an unbelievably high price.|||친구가 터무니없는 가격을 말한다.|||말도 안 돼|||말도 안 돼 (Mal-do an-dwae)|||“That makes no sense” used for strong denial.|||설마 그게 돼? (Seol-ma geu-ge dwae?)|||Doubt, not rejection.|||헐 진짜? (Heol jin-jja?)|||Shock.|||와 대박이다 (Wa dae-bak-i-da)|||Positive reaction.
17|||Your friend shows you an unbelievable result.|||친구가 말도 안 되는 결과를 보여준다.|||미쳤다|||미쳤다 (Mi-chyeot-da)|||“That’s crazy (in a good way)” used for positive shock.|||말도 안 돼 (Mal-do an-dwae)|||Denial.|||헐 진짜? (Heol jin-jja?)|||Shock + confirm.|||설마 그게 돼? (Seol-ma geu-ge dwae?)|||Doubt.
18|||You watch a video and slowly start laughing harder and harder.|||영상을 보다가 점점 웃음이 터진다.|||너무 웃겨|||너무 웃겨 (Neo-mu ut-gyeo)|||“This is so funny” used when laughter builds up.|||미쳤다 (Mi-chyeot-da)|||Positive shock.|||말도 안 돼 (Mal-do an-dwae)|||Denial.|||설마 그게 돼? (Seol-ma geu-ge dwae?)|||Doubt.
19|||You hear your friend’s point and completely agree.|||친구 말을 듣고 완전히 납득한다.|||나도 인정|||나도 인정 (Na-do in-jeong)|||“I agree / I admit it” used with respect.|||응응 (Eung-eung)|||Casual agreement.|||오케이 (O-ke-i)|||Simple acceptance.|||맞아 (Mat-a)|||Agreement, but less “respect” nuance.
20|||Your friend is late and you want them to hurry.|||친구가 계속 늦고 있어서 빨리 오라고 한다.|||빨리 와|||빨리 와 (Ppal-li wa)|||“Come quickly” used to push action.|||기다려 (Gi-da-ryeo)|||“Wait.”|||오케이 (O-ke-i)|||Agreement.|||가자 (Ga-ja)|||“Let’s go.”
21|||Your friend shows you a travel plan on their phone.|||친구가 여행 계획을 보여준다.|||완전 좋아|||완전 좋아 (Wan-jeon jo-a)|||“I really like it” used for clear, confirmed satisfaction.|||대박 (Dae-bak)|||Strong excitement, not calm approval.|||좋다 (Jo-da)|||Too neutral.|||괜찮네 (Gwaen-chan-ne)|||Mild approval.
22|||You see a puppy acting cute.|||강아지가 애교를 부린다.|||너무 귀엽다|||너무 귀엽다 (Neo-mu gwi-yeop-da)|||“So cute” used with soft, warm emotion.|||대박 (Dae-bak)|||Too strong and energetic.|||헐 (Heol)|||Shock.|||좋다 (Jo-da)|||Too plain.
23|||You hear a strange noise in a quiet night.|||조용한 밤에 이상한 소리가 들린다.|||좀 무섭다|||좀 무섭다 (Jom mu-seop-da)|||“A bit scary” used for low-level fear.|||무섭다 (Mu-seop-da)|||Too strong.|||헐 (Heol)|||Shock.|||대박 (Dae-bak)|||Positive reaction.
24|||You watch a very touching scene.|||감동적인 장면을 본다.|||눈물 나|||눈물 나 (Nun-mul na)|||“It makes me tear up” used for emotional build-up.|||슬프다 (Seul-peu-da)|||Just sad, not emotional build.|||대박 (Dae-bak)|||Positive reaction.|||헐 (Heol)|||Shock.
25|||Right before starting something important, you raise the energy.|||무언가 시작하기 직전 분위기를 끌어올린다.|||가보자|||가보자 (Ga-bo-ja)|||“Let’s go” used to push energy forward.|||시작하자 (Si-jak-ha-ja)|||Too literal.|||오케이 (O-ke-i)|||Just agreement.|||힘내 (Him-nae)|||Encouragement, not push.
26|||Your friend shows you something they made alone, and it's amazing.|||친구가 혼자 만든 결과물을 보여주는데 압도적이다.|||미쳤다 이건|||미쳤다 이건 (Mi-chyeot-da i-geon)|||“This is insane” used with awe and object-focused evaluation.|||대박 (Dae-bak)|||General excitement.|||미쳤다 (Mi-chyeot-da)|||Lacks object emphasis.|||이거 레전드다 (I-geo re-jeon-deu-da)|||Higher hype tone.
27|||Your friend is going too far joking about someone.|||친구가 누군가를 과하게 놀린다.|||와 이건 좀 심하다|||와 이건 좀 심하다 (Wa i-geon jom sim-ha-da)|||“That’s too much” used for moral judgment.|||그만해 (Geu-man-hae)|||Direct stop.|||어이없어 (Eo-i-eop-seo)|||Emotional reaction.|||말도 안 돼 (Mal-do an-dwae)|||Logical denial.
28|||Your friend crosses the line with what they say.|||친구가 선을 넘는 말을 한다.|||그건 좀 아니지|||그건 좀 아니지 (Geu-geon jom a-ni-ji)|||“That’s not okay” used to set a boundary calmly.|||와 이건 좀 심하다 (Wa i-geon jom sim-ha-da)|||Judgment, not boundary.|||말도 안 돼 (Mal-do an-dwae)|||Denial.|||어이없어 (Eo-i-eop-seo)|||Emotional.
29|||Your friend performs something incredibly impressive.|||친구의 퍼포먼스가 압도적이다.|||이거 레전드다|||이거 레전드다 (I-geo re-jeon-deu-da)|||“This is legendary” used for top-level praise.|||대박 (Dae-bak)|||One level lower.|||미쳤다 이건 (Mi-chyeot-da i-geon)|||Awe + object focus.|||완전 좋아 (Wan-jeon jo-a)|||Satisfaction, not hype.
30|||You hear something that makes no logical sense at all.|||상식적으로 말이 안 되는 이야기를 듣는다.|||진짜 말도 안 돼|||진짜 말도 안 돼 (Jin-jja mal-do an-dwae)|||“This seriously makes no sense” used for strong judgment.|||말도 안 돼 (Mal-do an-dwae)|||Weaker.|||설마 (Seol-ma)|||Doubt, not judgment.|||헐 (Heol)|||Shock.
31|||You find something that perfectly matches your taste.|||취향에 딱 맞는 결과를 발견한다.|||완전 내 스타일이야|||완전 내 스타일이야 (Wan-jeon nae seu-ta-il-i-ya)|||“This is totally my style” used for taste alignment.|||완전 좋아 (Wan-jeon jo-a)|||General approval.|||대박 (Dae-bak)|||Excited reaction.|||괜찮네 (Gwaen-chan-ne)|||Mild approval.
32|||You see a result that exceeds expectations and acknowledge it.|||기대 이상 결과를 보고 인정한다.|||이건 인정이다|||이건 인정이다 (I-geon in-jeong-i-da)|||“I have to admit this” used for clear recognition.|||나도 인정 (Na-do in-jeong)|||Agreement, not evaluation.|||대박 (Dae-bak)|||Excitement.|||완전 좋아 (Wan-jeon jo-a)|||Satisfaction.
33|||Things keep not working and frustration builds up.|||상황이 계속 안 풀려 답답함이 쌓인다.|||너무 답답하다|||너무 답답하다 (Neo-mu dap-dap-ha-da)|||“This is so frustrating” used for built-up tension.|||진짜 짜증난다 (Jin-jja jja-jeung-nan-da)|||Strong irritation.|||말도 안 돼 (Mal-do an-dwae)|||Denial.|||어이없어 (Eo-i-eop-seo)|||Absurd reaction.
34|||The same mistake keeps happening and it annoys you.|||같은 실수가 반복되어 짜증이 난다.|||진짜 짜증난다|||진짜 짜증난다 (Jin-jja jja-jeung-nan-da)|||“This is really annoying” used for irritation peak.|||너무 답답하다 (Neo-mu dap-dap-ha-da)|||Lower-level frustration.|||어이없어 (Eo-i-eop-seo)|||Absurd reaction.|||말도 안 돼 (Mal-do an-dwae)|||Denial.
35|||You expected something to be bad, but it's actually okay.|||기대가 낮았는데 생각보다 괜찮다.|||생각보다 괜찮은데?|||생각보다 괜찮은데? (Saeng-gak-bo-da gwaen-chan-eun-de?)|||“Better than I expected” used for re-evaluation.|||괜찮네 (Gwaen-chan-ne)|||Just neutral.|||완전 좋아 (Wan-jeon jo-a)|||Strong approval.|||대박 (Dae-bak)|||Excitement.
36|||Something turns out to be way more fun than expected.|||기대 안 했는데 너무 재미있다.|||완전 꿀잼이다|||완전 꿀잼이다 (Wan-jeon kkul-jaem-i-da)|||“This is super fun” used for high-level enjoyment evaluation.|||너무 웃겨 (Neo-mu ut-gyeo)|||Laugh reaction.|||대박 (Dae-bak)|||Excitement.|||재밌다 (Jae-mit-da)|||Basic expression.
37|||You expected something to be fun, but it’s boring.|||기대했는데 재미없다.|||이건 노잼이다|||이건 노잼이다 (I-geon no-jaem-i-da)|||“This is not fun” used for low enjoyment judgment.|||재미없다 (Jae-mi-eop-da)|||Basic statement.|||별로다 (Byeol-lo-da)|||General dislike.|||지루하다 (Ji-ru-ha-da)|||Bored feeling.
38|||You experience a strange, unexplainable moment.|||설명하기 어려운 이상한 순간을 느낀다.|||진짜 소름 돋는다|||진짜 소름 돋는다 (Jin-jja so-reum dot-neun-da)|||“This gives me chills” used for awe-type reaction.|||무섭다 (Mu-seop-da)|||Fear.|||헐 (Heol)|||Shock.|||대박 (Dae-bak)|||Positive reaction.
39|||Your friend gets a great opportunity and you feel happy but envious.|||친구가 좋은 기회를 얻어 부럽다.|||너무 부럽다|||너무 부럽다 (Neo-mu bu-reop-da)|||“I’m so jealous (in a good way)” used for positive envy.|||좋겠다 (Jo-get-da)|||Light envy.|||대박 (Dae-bak)|||Excitement.|||축하해 (Chuk-ha-hae)|||Congratulation.
40|||Something is funny but also a bit sad at the same time.|||웃긴데 동시에 슬프다.|||이건 좀 웃프다|||이건 좀 웃프다 (I-geon jom ut-peu-da)|||“This is funny but sad” used for mixed emotion.|||슬프다 (Seul-peu-da)|||Sad only.|||웃기다 (Ut-gi-da)|||Funny only.|||어이없어 (Eo-i-eop-seo)|||Absurd.
41|||During a conversation, one comment suddenly makes the atmosphere awkward.|||대화 중 한마디로 분위기가 갑자기 싸해진다.|||분위기 갑자기 싸해졌다|||분위기 갑자기 싸해졌다 (Bun-wi-gi gap-ja-gi ssa-hae-jyeot-da)|||“The mood suddenly turned cold” used to notice a shift in atmosphere.|||어색하다 (Eo-saek-ha-da)|||Just awkward.|||조용해졌다 (Jo-yong-hae-jyeot-da)|||Became quiet.|||이상하다 (I-sang-ha-da)|||Something feels off.
42|||You see two things that match perfectly together.|||조합이 너무 잘 맞는다.|||이거 완전 찰떡이다|||이거 완전 찰떡이다 (I-geo wan-jeon chal-tteok-i-da)|||“This is a perfect match” used for ideal combination.|||완전 좋아 (Wan-jeon jo-a)|||General approval.|||잘 어울린다 (Jal eo-ul-lin-da)|||Matches well.|||대박 (Dae-bak)|||Excited reaction.
43|||You see a sweet couple moment.|||달콤한 커플 장면을 본다.|||너무 달달하다|||너무 달달하다 (Neo-mu dal-dal-ha-da)|||“So sweet” used for relationship-based emotion.|||너무 귀엽다 (Neo-mu gwi-yeop-da)|||Cute, not relational.|||좋다 (Jo-da)|||Too general.|||대박 (Dae-bak)|||Too energetic.
44|||You feel quiet sympathy for a bittersweet situation.|||안타깝지만 조용히 공감하게 된다.|||마음이 좀 짠하다|||마음이 좀 짠하다 (Ma-eum-i jom jjan-ha-da)|||“It feels bittersweet” used for quiet empathy.|||슬프다 (Seul-peu-da)|||Just sadness.|||눈물 난다 (Nun-mul nan-da)|||Emotional release.|||안타깝다 (An-ta-kkap-da)|||Descriptive, not feeling.
45|||Someone clearly crosses the line.|||상대가 명확히 선을 넘는다.|||선 넘었다|||선 넘었다 (Seon neo-meot-da)|||“That crossed the line” used for final boundary judgment.|||그건 좀 아니지 (Geu-geon jom a-ni-ji)|||Softer boundary.|||와 이건 좀 심하다 (Wa i-geon jom sim-ha-da)|||Moral judgment.|||말도 안 돼 (Mal-do an-dwae)|||Denial.
46|||You hear something that makes no sense at all and react strongly.|||상식적으로 납득이 안 되는 이야기를 듣는다.|||야 이건 진짜 말도 안 된다|||야 이건 진짜 말도 안 된다 (Ya i-geon jin-jja mal-do an-dwae-da)|||“Hey, this seriously makes no sense” used for strong opinion.|||말도 안 돼 (Mal-do an-dwae)|||Basic denial.|||진짜 말도 안 돼 (Jin-jja mal-do an-dwae)|||Strong denial, less conversational.|||어이없어 (Eo-i-eop-seo)|||Emotional reaction.
47|||You hear something unexpected and react honestly.|||예상 못한 사실을 듣고 솔직하게 반응한다.|||솔직히 좀 충격인데?|||솔직히 좀 충격인데? (Sol-jik-hi jom chung-gyeok-in-de?)|||“Honestly, that’s kind of shocking” used for honest reaction.|||헐 진짜? (Heol jin-jja?)|||Shock + confirm.|||진짜야? (Jin-jja-ya?)|||Confirmation.|||대박 (Dae-bak)|||Excitement.
48|||You point out someone's behavior calmly but firmly.|||상대 행동을 감정 없이 짚는다.|||아니 이건 너무한 거 아니야?|||아니 이건 너무한 거 아니야? (A-ni i-geon neo-mu-han geo a-ni-ya?)|||“Isn’t that too much?” used for calm authority.|||그건 좀 아니지 (Geu-geon jom a-ni-ji)|||Boundary.|||와 이건 좀 심하다 (Wa i-geon jom sim-ha-da)|||Judgment.|||말도 안 돼 (Mal-do an-dwae)|||Denial.
49|||You acknowledge someone’s skill respectfully.|||상대 실력을 인정한다.|||이건 인정이다|||이건 인정이다 (I-geon in-jeong-i-da)|||“I have to admit this” used for respectful recognition.|||나도 인정 (Na-do in-jeong)|||Agreement.|||대박 (Dae-bak)|||Excitement.|||잘했다 (Jal-haet-da)|||Simple praise.
50|||You notice something unexpectedly funny and share it.|||상황이 의외로 웃겨서 공유한다.|||이건 좀 웃긴데?|||이건 좀 웃긴데? (I-geon jom ut-gin-de?)|||“That’s kind of funny” used to share light humor.|||너무 웃겨 (Neo-mu ut-gyeo)|||Strong laugh.|||웃기다 (Ut-gi-da)|||Statement.|||재밌다 (Jae-mit-da)|||General fun.
51|||You and your friend watch something amazing together and react at the same time.|||둘이 함께 본 장면이 너무 압도적이다.|||와 이건 진짜 레전드다|||와 이건 진짜 레전드다 (Wa i-geon jin-jja re-jeon-deu-da)|||“Wow, this is truly legendary” used for shared awe.|||이거 레전드다 (I-geo re-jeon-deu-da)|||Strong praise, but not shared.|||대박 (Dae-bak)|||Excited reaction.|||미쳤다 이건 (Mi-chyeot-da i-geon)|||Awe, object-focused.
52|||Your friend says something so absurd you almost laugh.|||상대 말이 너무 황당해서 웃음이 나오기 직전이다.|||너 지금 장난하는 거지?|||너 지금 장난하는 거지? (Neo ji-geum jang-nan-ha-neun geo-ji?)|||“You’re kidding, right?” used for absurd but playful disbelief.|||말도 안 돼 (Mal-do an-dwae)|||Strong denial.|||설마 (Seol-ma)|||Doubt.|||헐 진짜? (Heol jin-jja?)|||Shock + confirm.
53|||You saw something amazing and share your feeling with someone.|||경이로운 장면을 보고 경험을 공유한다.|||나 이거 보고 소름 돋았어|||나 이거 보고 소름 돋았어 (Na i-geo bo-go so-reum do-dat-eo)|||“I got chills watching this” used for personal experience sharing.|||진짜 소름 돋는다 (Jin-jja so-reum dot-neun-da)|||Immediate reaction.|||헐 (Heol)|||Shock.|||대박 (Dae-bak)|||Excited reaction.
54|||You didn’t expect much, but it turned out okay, so you share your opinion.|||기대 안 했는데 괜찮아서 의견을 전달한다.|||이건 좀 생각보다 괜찮다|||이건 좀 생각보다 괜찮다 (I-geon jom saeng-gak-bo-da gwaen-chan-ta)|||“This is better than expected” used for re-evaluation sharing.|||생각보다 괜찮은데? (Saeng-gak-bo-da gwaen-chan-eun-de?)|||More internal reaction.|||완전 좋아 (Wan-jeon jo-a)|||Strong approval.|||대박 (Dae-bak)|||Excitement.
55|||Someone says something that hurts you, so you express it calmly.|||상대 말에 상처받았지만 차분하게 전달한다.|||솔직히 기분 좀 상했어|||솔직히 기분 좀 상했어 (Sol-jik-hi gi-bun jom sang-haet-eo)|||“Honestly, that hurt my feelings” used for calm emotional delivery.|||기분 나쁘다 (Gi-bun na-ppeu-da)|||Strong and blunt.|||짜증난다 (Jja-jeung-nan-da)|||Irritation.|||어이없어 (Eo-i-eop-seo)|||Absurd reaction.
56|||You decide that something cannot just be ignored.|||그냥 넘어가면 안 되는 상황이라고 판단한다.|||이건 그냥 넘어가기 어렵다|||이건 그냥 넘어가기 어렵다 (I-geon geu-nyang neo-meo-ga-gi eo-ryeop-da)|||“This is hard to just let go” used for firm stance.|||그건 좀 아니지 (Geu-geon jom a-ni-ji)|||Boundary.|||와 이건 좀 심하다 (Wa i-geon jom sim-ha-da)|||Judgment.|||말도 안 돼 (Mal-do an-dwae)|||Denial.
57|||A frustrating situation finally gets resolved.|||답답했던 상황이 해결된다.|||와 속이 다 시원하다|||와 속이 다 시원하다 (Wa sok-i da si-won-ha-da)|||“I feel so relieved” used for emotional release.|||다행이다 (Da-haeng-i-da)|||Relief, but lighter.|||좋다 (Jo-da)|||Simple.|||끝났다 (Kkeut-nat-da)|||Just completion.
58|||You are so frustrated that you physically can't keep watching.|||답답함이 극에 달해 더 못 보겠다.|||너무 답답해서 못 보겠다|||너무 답답해서 못 보겠다 (Neo-mu dap-dap-hae-seo mot bo-get-da)|||“I can’t watch this anymore” due to overload.|||너무 답답하다 (Neo-mu dap-dap-ha-da)|||Just feeling.|||짜증난다 (Jja-jeung-nan-da)|||Irritation.|||화난다 (Hwa-nan-da)|||Anger.
59|||The mood suddenly becomes awkward and you react to it.|||분위기가 갑자기 어색해진다.|||이 분위기 갑자기 왜 이래?|||이 분위기 갑자기 왜 이래? (I bun-wi-gi gap-ja-gi wae i-rae?)|||“Why did it suddenly get awkward?” used to question mood shift.|||분위기 싸해졌다 (Bun-wi-gi ssa-hae-jyeot-da)|||Observation.|||어색하다 (Eo-saek-ha-da)|||Description.|||이상하다 (I-sang-ha-da)|||Something feels off.
60|||You suddenly realize reality and feel mentally drained.|||현실을 자각하며 멘탈이 무너진다.|||나 지금 현타 왔어|||나 지금 현타 왔어 (Na ji-geum hyeon-ta wat-eo)|||“I’m having a reality check” used for mental collapse.|||피곤하다 (Pi-gon-ha-da)|||Tired.|||힘들다 (Him-deul-da)|||Hard.|||멘붕이다 (Men-bung-i-da)|||Breakdown, but stronger expression.
61|||You see something overly emotional and feel a bit embarrassed in a cute way.|||과하게 감성적인 행동을 보고 민망해진다.|||이건 좀 오글거린다|||이건 좀 오글거린다 (I-geon jom o-geul-geo-rin-da)|||“This is a bit cringey” used for cute, light embarrassment.|||부끄럽다 (Bu-kkeu-reop-da)|||Just shy.|||어색하다 (Eo-saek-ha-da)|||Awkward.|||싫다 (Sil-ta)|||Negative rejection.
62|||You watch something emotional together and share the feeling.|||감동적인 장면을 함께 본다.|||와 진짜 눈물 난다|||와 진짜 눈물 난다 (Wa jin-jja nun-mul nan-da)|||“Wow, this makes me tear up” used for shared emotion.|||눈물 나 (Nun-mul na)|||Personal emotion.|||슬프다 (Seul-peu-da)|||Sad only.|||감동이다 (Gam-dong-i-da)|||Statement.
63|||You find something that matches your taste and share it with someone.|||취향에 맞는 것을 발견하고 공유한다.|||이거 완전 내 취향이다|||이거 완전 내 취향이다 (I-geo wan-jeon nae chwi-hyang-i-da)|||“This is totally my taste” used for shared preference.|||완전 내 스타일이야 (Wan-jeon nae seu-ta-il-i-ya)|||Personal statement.|||좋다 (Jo-da)|||General.|||괜찮다 (Gwaen-chan-ta)|||Mild.
64|||Someone achieves something impressive and you acknowledge it with respect.|||상대가 어려운 일을 해낸다.|||너 진짜 대단하다|||너 진짜 대단하다 (Neo jin-jja dae-dan-ha-da)|||“You’re really amazing” used with deep respect.|||잘했다 (Jal-haet-da)|||Simple praise.|||대박이다 (Dae-bak-i-da)|||Excitement.|||멋있다 (Meot-it-da)|||Admiration.
65|||You feel something is unfair and express it.|||상황이 불공평하게 느껴진다.|||이건 좀 억울한데?|||이건 좀 억울한데? (I-geon jom eok-ul-han-de?)|||“This feels unfair” used for expressing injustice.|||짜증난다 (Jja-jeung-nan-da)|||Irritation.|||화난다 (Hwa-nan-da)|||Anger.|||말도 안 돼 (Mal-do an-dwae)|||Denial.
66|||Someone asks you to apologize and you question it logically.|||이유 없이 사과를 요구받는다.|||아니 왜 내가 미안해야 돼?|||아니 왜 내가 미안해야 돼? (A-ni wae nae-ga mi-an-hae-ya dwae?)|||“Why should I apologize?” used as a calm logical question.|||말도 안 돼 (Mal-do an-dwae)|||Denial.|||그건 좀 아니지 (Geu-geon jom a-ni-ji)|||Boundary.|||짜증난다 (Jja-jeung-nan-da)|||Emotion.
67|||Someone asks too much and you push back gently.|||요구가 과해서 부드럽게 거절한다.|||이건 좀 무리 아니야?|||이건 좀 무리 아니야? (I-geon jom mu-ri a-ni-ya?)|||“Isn’t that too much?” used for soft limit setting.|||못 해 (Mot hae)|||Direct refusal.|||그건 좀 아니지 (Geu-geon jom a-ni-ji)|||Boundary.|||힘들다 (Him-deul-da)|||Personal difficulty.
68|||You see something that exceeds expectations and react.|||기대 이상 결과를 본다.|||와 이건 상상 이상이다|||와 이건 상상 이상이다 (Wa i-geon sang-sang i-sang-i-da)|||“This is beyond imagination” used for high evaluation.|||대박 (Dae-bak)|||Excitement.|||미쳤다 (Mi-chyeot-da)|||Shock.|||완전 좋아 (Wan-jeon jo-a)|||Satisfaction.
69|||You see something valuable and decide to learn it.|||배울 가치가 있다고 느낀다.|||이건 진짜 배워야겠다|||이건 진짜 배워야겠다 (I-geon jin-jja bae-wo-ya-get-da)|||“I should really learn this” used for action decision.|||좋다 (Jo-da)|||Positive.|||대박 (Dae-bak)|||Excitement.|||괜찮다 (Gwaen-chan-ta)|||Mild.
70|||You finally understand something after struggling.|||이해가 안 되던 것이 풀린다.|||이제야 감 잡았다|||이제야 감 잡았다 (I-je-ya gam jap-at-da)|||“Now I finally get it” used for eureka moment.|||이해했다 (I-hae-haet-da)|||Basic.|||알겠다 (Al-get-da)|||Light understanding.|||오케이 (O-ke-i)|||Agreement.
71|||You disagree with someone's opinion but avoid direct conflict.|||상대 의견이 납득되지 않지만 정면 충돌은 피한다.|||솔직히 이해는 안 된다|||솔직히 이해는 안 된다 (Sol-jik-hi i-hae-neun an doen-da)|||“Honestly, I don’t understand” used for calm disagreement.|||말도 안 돼 (Mal-do an-dwae)|||Strong denial.|||그건 좀 아니지 (Geu-geon jom a-ni-ji)|||Boundary.|||이상하다 (I-sang-ha-da)|||Something feels off.
72|||You partially agree but leave room without fully committing.|||일부는 인정하지만 완전히 동의하지 않는다.|||그럴 수도 있긴 한데…|||그럴 수도 있긴 한데… (Geu-reol su-do it-gin han-de…)|||“That could be true, but…” used to hold distance.|||맞아 (Mat-a)|||Full agreement.|||아닌 것 같다 (A-nin geot gat-da)|||More direct disagreement.|||음… (Eum…)|||Just hesitation.
73|||You need to reject a suggestion politely.|||제안을 완곡하게 거절해야 한다.|||음… 이건 아닌 것 같다|||음… 이건 아닌 것 같다 (Eum… i-geon a-nin geot gat-da)|||“Hmm… I don’t think this is right” used for soft refusal.|||싫다 (Sil-ta)|||Direct rejection.|||안 된다 (An doen-da)|||Firm refusal.|||별로다 (Byeol-lo-da)|||Dislike.
74|||You accept the logic but feel emotionally uncomfortable.|||논리는 맞지만 감정이 불편하다.|||말은 맞는데 기분은 별로다|||말은 맞는데 기분은 별로다 (Mal-eun mat-neun-de gi-bun-eun byeol-lo-da)|||“You’re right, but I don’t feel good about it” used for logic vs emotion.|||말도 안 돼 (Mal-do an-dwae)|||Denial.|||그건 좀 아니지 (Geu-geon jom a-ni-ji)|||Boundary.|||어이없어 (Eo-i-eop-seo)|||Emotional reaction.
75|||Someone crosses a line, and you point it out calmly.|||상대가 선을 넘었지만 완곡하게 말한다.|||이건 좀 선 넘은 것 같다|||이건 좀 선 넘은 것 같다 (I-geon jom seon neo-meon geot gat-da)|||“I think that crossed the line” used for soft boundary.|||선 넘었다 (Seon neo-meot-da)|||Final judgment.|||그건 좀 아니지 (Geu-geon jom a-ni-ji)|||Boundary.|||와 이건 좀 심하다 (Wa i-geon jom sim-ha-da)|||Moral judgment.
76|||Something isn’t bad, but you’re unsure about it.|||완전히 나쁘진 않지만 확신이 없다.|||나쁘진 않은데 애매하다|||나쁘진 않은데 애매하다 (Na-ppeu-jin an-eun-de ae-mae-ha-da)|||“It’s not bad, but it’s unclear” used for neutral ambiguity.|||괜찮다 (Gwaen-chan-ta)|||Positive.|||별로다 (Byeol-lo-da)|||Negative.|||좋다 (Jo-da)|||Positive.
77|||You understand someone’s good intention but feel uncomfortable.|||상대의 호의는 이해하지만 부담스럽다.|||좋은 뜻인 건 알겠는데 부담스럽다|||좋은 뜻인 건 알겠는데 부담스럽다 (Jo-eun tteus-in geon al-get-neun-de bu-dam-seu-reop-da)|||“I know you mean well, but it’s a bit much” used for polite discomfort.|||고맙다 (Go-map-da)|||Gratitude.|||싫다 (Sil-ta)|||Direct rejection.|||괜찮다 (Gwaen-chan-ta)|||Acceptance.
78|||Something starts funny but slowly becomes uncomfortable.|||처음엔 웃기지만 점점 불편해진다.|||웃기긴 한데 좀 불편하다|||웃기긴 한데 좀 불편하다 (Ut-gi-gin han-de jom bul-pyeon-ha-da)|||“It’s funny, but also uncomfortable” used for slow mood shift.|||웃기다 (Ut-gi-da)|||Funny.|||별로다 (Byeol-lo-da)|||Dislike.|||어이없어 (Eo-i-eop-seo)|||Absurd.
79|||You think someone didn’t mean harm and soften the situation.|||상대가 일부러 그런 건 아닐 수 있다고 본다.|||일부러 그런 건 아닌 것 같다|||일부러 그런 건 아닌 것 같다 (Il-bu-reo geu-reon geon a-nin geot gat-da)|||“I don’t think they meant it” used to soften intent.|||그건 좀 아니지 (Geu-geon jom a-ni-ji)|||Boundary.|||잘못했다 (Jal-mot-haet-da)|||Blame.|||어이없어 (Eo-i-eop-seo)|||Emotion.
80|||You decide it's better not to bring something up in the current situation.|||지금은 그냥 넘어가는 게 낫다고 판단한다.|||분위기상 그냥 넘어가는 게 낫다|||분위기상 그냥 넘어가는 게 낫다 (Bun-wi-gi-sang geu-nyang neo-meo-ga-neun ge nat-da)|||“Given the situation, it’s better to let it go” used for social strategy.|||넘어가자 (Neo-meo-ga-ja)|||Suggestion.|||괜찮다 (Gwaen-chan-ta)|||Acceptance.|||참자 (Cham-ja)|||Endure.
81|||You decide it's better to stay quiet to avoid making things worse.|||지금 말하면 상황이 더 나빠질 것 같다고 판단한다.|||지금은 말 아끼는 게 좋겠다|||지금은 말 아끼는 게 좋겠다 (Ji-geum-eun mal a-kki-neun ge jot-get-da)|||“It’s better to hold back right now” used for strategic silence.|||말하지 말자 (Mal-ha-ji mal-ja)|||Direct.|||조용히 하자 (Jo-yong-hi ha-ja)|||Control.|||넘어가자 (Neo-meo-ga-ja)|||Let go.
82|||You feel someone truly deserves to be congratulated.|||진심으로 축하해야 하는 상황이다.|||이건 진심으로 축하해줘야 한다|||이건 진심으로 축하해줘야 한다 (I-geon jin-sim-eu-ro chuk-ha-hae-jwo-ya han-da)|||“This really deserves congratulations” used as social norm.|||축하해 (Chuk-ha-hae)|||Basic.|||대단하다 (Dae-dan-ha-da)|||Admiration.|||잘했다 (Jal-haet-da)|||Praise.
83|||Someone says they're fine, but you think they might be hurt inside.|||겉으로는 괜찮다고 하지만 속은 아닐 수 있다.|||겉으로는 괜찮다고 해도 속상할 수 있다|||겉으로는 괜찮다고 해도 속상할 수 있다 (Geot-eu-ro-neun gwaen-chan-ta-go hae-do sok-sang-hal su it-da)|||“Even if they seem fine, they could be hurt” used for deep empathy.|||괜찮다 (Gwaen-chan-ta)|||Surface.|||속상하다 (Sok-sang-ha-da)|||Emotion only.|||안타깝다 (An-ta-kkap-da)|||Sympathy.
84|||A foreigner’s words could be misunderstood in Korean context.|||외국인의 말이 오해될 수 있다.|||한국에서는 이 말이 장난처럼 들릴 수 있다|||한국에서는 이 말이 장난처럼 들릴 수 있다 (Han-guk-e-seo-neun i mal-i jang-nan-cheo-reom deul-ril su it-da)|||“In Korea, this might sound like a joke” used for cultural explanation.|||오해할 수 있다 (O-hae-hal su it-da)|||General.|||이상하다 (I-sang-ha-da)|||Odd.|||괜찮다 (Gwaen-chan-ta)|||Fine.
85|||It’s better to speak indirectly in this situation.|||직접 말하면 어색한 상황이다.|||이 상황에서는 돌려 말하는 게 자연스럽다|||이 상황에서는 돌려 말하는 게 자연스럽다 (I sang-hwang-e-seo-neun dol-lyeo mal-ha-neun ge ja-yeon-seu-reop-da)|||“It’s more natural to speak indirectly here” used for cultural strategy.|||직접 말하자 (Jik-jeop mal-ha-ja)|||Direct.|||말하지 말자 (Mal-ha-ji mal-ja)|||Silence.|||넘어가자 (Neo-meo-ga-ja)|||Avoid.
86|||Someone doesn’t understand why people reacted a certain way.|||왜 그렇게 반응했는지 이해 못한다.|||한국에서는 이런 상황에서 이렇게 반응하는 편이다|||한국에서는 이런 상황에서 이렇게 반응하는 편이다 (Han-guk-e-seo-neun i-reon sang-hwang-e-seo i-reo-ke ban-eung-ha-neun pyeon-i-da)|||“In Korea, people tend to react this way” used for general insight.|||이상하다 (I-sang-ha-da)|||Odd.|||왜 그랬지 (Wae geu-raet-ji)|||Question.|||몰랐다 (Mol-lat-da)|||Didn’t know.
87|||Someone’s polite words don’t reflect their real intention.|||겉말과 속뜻이 다르다.|||이건 예의상 그렇게 말한 거다|||이건 예의상 그렇게 말한 거다 (I-geon ye-ui-sang geu-reo-ke mal-han geo-da)|||“They said that out of politeness” used to decode intention.|||진짜다 (Jin-jja-da)|||Literal.|||괜찮다 (Gwaen-chan-ta)|||Accept.|||좋다 (Jo-da)|||Positive.
88|||What seems like emotion is actually just a way of expression.|||감정처럼 보이지만 표현 방식일 뿐이다.|||이건 진짜 감정이 아니라 표현 방식이다|||이건 진짜 감정이 아니라 표현 방식이다 (I-geon jin-jja gam-jeong-i a-ni-ra pyo-hyeon bang-sik-i-da)|||“This isn’t real emotion, it’s just expression” used for analysis.|||화났다 (Hwa-nat-da)|||Emotion.|||기분 나쁘다 (Gi-bun na-ppeu-da)|||Feeling.|||이상하다 (I-sang-ha-da)|||Vague.
89|||You explain that someone’s words make sense when considering the situation.|||맥락을 보면 이해된다.|||상황을 보면 그렇게 말할 수밖에 없다|||상황을 보면 그렇게 말할 수밖에 없다 (Sang-hwang-eul bo-myeon geu-reo-ke mal-hal su-bak-e eop-da)|||“Given the situation, they had no choice but to say that” used as mediator insight.|||이해된다 (I-hae-doen-da)|||Simple.|||그럴 수도 있다 (Geu-reol su-do it-da)|||Possibility.|||맞다 (Mat-da)|||Agreement.
90|||You realize a simple phrase carries deeper meaning.|||단순한 말 속에 깊은 의미가 있다.|||이건 단순한 말이 아니라 의미가 담겨 있다|||이건 단순한 말이 아니라 의미가 담겨 있다 (I-geon dan-sun-han mal-i a-ni-ra ui-mi-ga dam-gyeo it-da)|||“This isn’t just words, it has deeper meaning” used for final insight.|||의미 있다 (Ui-mi it-da)|||Simple.|||중요하다 (Jung-yo-ha-da)|||Important.|||좋다 (Jo-da)|||Positive.
91|||You realize the issue is not the event itself, but the relationship behind it.|||문제의 본질이 사건이 아니라 관계임을 깨닫는다.|||이건 결국 관계의 문제다|||이건 결국 관계의 문제다 (I-geon gyeol-guk gwan-gye-ui mun-je-da)|||“This is ultimately a relationship issue” used for core insight.|||상황이 문제다 (Sang-hwang-i mun-je-da)|||Situation-focused.|||이해가 안 된다 (I-hae-ga an doen-da)|||Confusion.|||복잡하다 (Bok-jap-ha-da)|||General.
92|||You understand that atmosphere matters more than words.|||말보다 분위기가 더 중요하다는 것을 깨닫는다.|||말보다 분위기가 더 중요하다|||말보다 분위기가 더 중요하다 (Mal-bo-da bun-wi-gi-ga deo jung-yo-ha-da)|||“The atmosphere matters more than words” used for priority shift.|||말이 중요하다 (Mal-i jung-yo-ha-da)|||Opposite.|||표현이 중요하다 (Pyo-hyeon-i jung-yo-ha-da)|||Expression.|||내용이 중요하다 (Nae-yong-i jung-yo-ha-da)|||Content.
93|||You realize that timing changes everything.|||같은 말도 타이밍에 따라 다름을 깨닫는다.|||이건 타이밍의 문제다|||이건 타이밍의 문제다 (I-geon ta-i-ming-ui mun-je-da)|||“This is a matter of timing” used for analytical insight.|||상황이 문제다 (Sang-hwang-i mun-je-da)|||Situation.|||방법이 문제다 (Bang-beop-i mun-je-da)|||Method.|||사람이 문제다 (Sa-ram-i mun-je-da)|||Person.
94|||You understand that both sides need to understand each other.|||양쪽 입장을 모두 고려해야 함을 느낀다.|||이건 서로 이해가 필요한 상황이다|||이건 서로 이해가 필요한 상황이다 (I-geon seo-ro i-hae-ga pil-yo-han sang-hwang-i-da)|||“This situation requires mutual understanding” used for balance.|||이해해야 한다 (I-hae-hae-ya han-da)|||General.|||참아야 한다 (Cham-a-ya han-da)|||Endure.|||넘어가야 한다 (Neo-meo-ga-ya han-da)|||Avoid.
95|||After everything, you realize how complex human emotions are.|||모든 과정을 거쳐 인간의 마음이 가장 어렵다는 것을 느낀다.|||결국 사람 마음이 제일 어렵다|||결국 사람 마음이 제일 어렵다 (Gyeol-guk sa-ram ma-eum-i je-il eo-ryeop-da)|||“In the end, the human heart is the hardest to understand” used as final message.|||사람이 어렵다 (Sa-ram-i eo-ryeop-da)|||Simplified.|||인생이 어렵다 (In-saeng-i eo-ryeop-da)|||Broader.|||복잡하다 (Bok-jap-ha-da)|||General.
'''.strip()

def split_field(s, sep='|||'):
    return s.split(sep)

def korean_only(labeled):
    # labeled like "헐 (Heol)" or "헐 진짜? (Heol jin-jja?)"
    if ' (' in labeled:
        return labeled.split(' (', 1)[0].strip()
    return labeled.strip()

def parse_block(block_lines):
    pass

out = []
def korean_only(full):
    i = full.find(' (')
    if i >= 0:
        return full[:i].strip()
    return full.strip()


out = []
for line in DATA.split('\n'):
    if not line.strip():
        continue
    parts = split_field(line)
    if len(parts) != 12:
        raise ValueError('bad field count %d id=%s' % (len(parts), parts[0] if parts else ''))
    qid = int(parts[0])
    qen = parts[1]
    qkr = parts[2]
    correct = parts[3]
    choice_fulls = [parts[4], parts[6], parts[8], parts[10]]
    choice_engs = [parts[5], parts[7], parts[9], parts[11]]
    choices = [korean_only(f) for f in choice_fulls]
    choice_labels = [('%s → %s' % (f, e)) for f, e in zip(choice_fulls, choice_engs)]
    if correct not in choices:
        raise ValueError('correct not in choices id=%d %r %r' % (qid, correct, choices))
    out.append({
        'id': qid,
        'correct': correct,
        'choices': choices,
        'choice_labels': choice_labels,
        'context_en': qen,
        'context_kr': qkr,
        'hint_video': '',
        'usage_level': 'SAFE',
    })

import sys
s = json.dumps(out, ensure_ascii=False, indent=2)
if len(sys.argv) > 1:
    with open(sys.argv[1], 'w', encoding='utf-8', newline='\n') as f:
        f.write(s)
else:
    sys.stdout.reconfigure(encoding='utf-8')
    print(s)
